TimeSheet/Controllers/ChatForumController.cs
namespace TimeSheet.Controllers
{
    using Properties;
    #region namespace

    using System;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using Models;
    using Repository;
    using System.Linq;
    using Timesheet.Common;

    #endregion namespae

    /// <summary>
    /// Hold Chat Forum Controller
    /// </summary>
    public class ChatForumController : Controller
    {
        /// <summary>
        /// holds chat detail model
        /// </summary>
        ChatViewModel chatDetailModel;

        /// <summary>
        /// dashboard Repository for database function
        /// </summary>
        DashboardRepository dashboardRepository;

        // GET: ChatForum
        public async Task<ActionResult> Index(string editId)
        {
            this.chatDetailModel = new ChatViewModel();

            if (!string.IsNullOrEmpty(editId))
            {
                this.dashboardRepository = new DashboardRepository();
                var issueDetailsList = await dashboardRepository.GetChatForumIssueList(editId);
                if (issueDetailsList != null)
                {
                    this.chatDetailModel.IssueDetails = issueDetailsList.First();
                }
            }

            return View(chatDetailModel);
        }

        /// <summary>
        /// method to save chat
        /// </summary>
        /// <param name="chatDetailModel"></param>
        /// <returns></returns>
        public async Task<ActionResult> SaveChatForum(ChatViewModel chatDetailModel)
        {
            try
            {
                if (chatDetailModel == null || chatDetailModel.IssueDetails == null)
                {
                    return Json("Something went wrong.");
                }

                this.dashboardRepository = new DashboardRepository();

                if (Session["LoginUserEmailId"] == null || string.IsNullOrEmpty(Session["LoginUserEmailId"].ToString()))
                {
                    return RedirectToAction("Logout", "Dashboard");
                }
                else
                {

                    chatDetailModel.IssueDetails.PostedBy = Session["LoginUserName"].ToString();
                    chatDetailModel.IssueDetails.EmailId = Session["LoginUserEmailId"].ToString();
                }

                var eId = await dashboardRepository.SaveChatForum(chatDetailModel.IssueDetails);

                if (!string.IsNullOrEmpty(chatDetailModel.IssueDetails.IssueId) && eId == 0)
                {
                    return Json("Issue updated successfully.");
                }
                else if (eId == 0 || eId == -1)
                {
                    return Json(Resources.CommonErorMessage);
                }
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }

            return Json("Issue Added Successfully!");
        }

        public async Task<ActionResult> GetChatForumDetailList()
        {
            try
            {
                this.dashboardRepository = new DashboardRepository();
                this.chatDetailModel = new ChatViewModel();
                this.chatDetailModel.IssueDetailsList = await dashboardRepository.GetChatForumIssueList(null);

                foreach (var issue in this.chatDetailModel.IssueDetailsList)
                {
                    issue.IsEditable = Session["LoginUserName"].ToString() == issue.PostedBy ? true : false;
                }
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }

            return View("chatForumView", this.chatDetailModel);
        }
    }
}

TimeSheet/Controllers/TimesheetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TimeSheet.Models;
using TimeSheet.Repository;
using TimeSheet.Properties;
using Timesheet.Common;

namespace TimeSheetControllers
{
    public class TimesheetController : Controller
    {
        TimesheetModel timesheetModel;

        public DashboardRepository dashboardRepository;

        // GET: Timesheet
        public async Task<ActionResult> Index(string editId)
        {
            timesheetModel = new TimesheetModel();
            timesheetModel.TimeEntryDetail = new TimeDetail();

            if (TimesheetSession.ProjectListSession == null || TimesheetSession.ProjectListSession.Count() == 0)
            {
                await timesheetModel.AssignProjectList();
                TimesheetSession.ProjectListSession = timesheetModel.ProjectList;
            }
            else
            {
                timesheetModel.ProjectList = TimesheetSession.ProjectListSession;
            }

            this.timesheetModel.TimeEntryDetail.Minutes = "0";
            this.timesheetModel.TimeEntryDetail.SubmitDate = DateTime.Now;
            if (!string.IsNullOrEmpty(editId))
            {
                this.dashboardRepository = new DashboardRepository();
                var workDetail = await this.dashboardRepository.GetWorkDetailListByFilter(Session["LoginUserId"].ToString(), null, null, null, editId);
                if (workDetail != null && workDetail.Count() > 0)
                {
                    this.timesheetModel.TimeEntryDetail = workDetail.First();
                }
            }

            return View(timesheetModel);
        }

        public async Task<ActionResult> SaveTimesheetEntry(TimesheetModel timesheetEntryDetail)
        {
            try
            {
                if (timesheetEntryDetail != null || timesheetEntryDetail.TimeEntryDetail != null)
                {
                    this.dashboardRepository = new DashboardRepository();

                    if (TimesheetSession.ProjectListSession == null || TimesheetSession.ProjectListSession.Count() == 0)
                    {
                        await timesheetModel.AssignProjectList();
                        TimesheetSession.ProjectListSession = timesheetModel.ProjectList;
                    }

                    timesheetEntryDetail.TimeEntryDetail.WorkProjectName = await Task.Run(() => TimesheetSession.ProjectListSession.FirstOrDefault(p => p.Id.Trim() == timesheetEntryDetail.TimeEntryDetail.ProjectName).Name);

                    if (Session["LoginUserId"] == null || string.IsNullOrEmpty(Session["LoginUserId"].ToString()))
                    {
                        return RedirectToAction("Logout", "Dashboard");
                    }
                    else
                    {
                        timesheetEntryDetail.TimeEntryDetail.EmployeeId = Session["LoginUserId"].ToString();
                        timesheetEntryDetail.TimeEntryDetail.EmployeeName = Session["LoginUserName"].ToString();
                    }
                    
                    var result = await dashboardRepository.AddWorkDetail(timesheetEntryDetail.TimeEntryDetail);

                    if (result == 0)
                    {
                        return Json(Resources.CommonErorMessage);
                    }
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return Json(e.Message);
            }

            return Json("Thanks You..!");
        }

        public async Task<ActionResult> DeleteWorkDetail(string deleteId)
        {
            try
            {
                if (string.IsNullOrEmpty(deleteId))
                {
                    return Json("Work detail Id Is Empty");
                }

                this.dashboardRepository = new DashboardRepository();

                var result = await this.dashboardRepository.DeleteWorkDetail(deleteId);

                return Json(result);

            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }
    }
}

TimeSheet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Timesheet</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/style.css" rel="stylesheet" />
</head>
<body class="fix-sidebar">

    <!-- Preloader -->
    <div class="preloader">
        <img src="~/images/wheel.gif" height="100" />
    </div>

    <div id="wrapper">
        <!-- Top Navigation -->
        @RenderPage("~/Views/Shared/menus.cshtml")
        <!-- End Top Navigation -->
        @*@RenderPage("~/Views/Shared/sidebar.cshtml")*@
        <!-- Left navbar-header end -->
        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <br />
                @RenderBody()
                <!-- .right-sidebar -->
            </div>
            <!-- /.container-fluid -->
            @*<footer class="footer text-center"> 2017 &copy; Utility Portal Master Admin </footer>*@
        </div>
        <!-- /#page-wrapper -->
    </div>
</body>
</html>

TimeSheet/Views/Shared/menus.cshtml
@using TimeSheet.Properties;

<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse slimscrollsidebar">
        <ul class="nav" id="side-menu">
            @*<li class="sidebar-search hidden-sm hidden-md hidden-lg">
                    <!-- input-group -->
                    <div class="input-group custom-search-form">
                        <input class="form-control" placeholder="@Resources.Search" type="text"> <span class="input-group-btn">
                            <button class="btn btn-default" type="button"> <i class="fa fa-search"></i> </button>
                        </span>
                    </div>
                    <!-- /input-group -->
                </li>*@
            <li>
                <a href="@Url.Action("Index", "Dashboard")" class="waves-effect"><i class="linea-icon linea-basic fa-fw"></i> <span class="hide-menu"> Dashboard <span class="fa arrow"></span> </span></a>
                @*<ul class="nav nav-second-level collapse" aria-expanded="true">
                        <li> <a href="index.html">Basic</a> </li>
                        <li> <a href="index2.html">Pending Approvals</a> </li>
                    </ul>*@
            </li>
            <li>
                <a href="@Url.Action("Index", "Timesheet", new { editId = string.Empty})" class="waves-effect"><i class="linea-icon linea-basic fa-fw"></i> <span class="hide-menu">Add Timesheet<span class="fa arrow"></span></span></a>
            </li>

            @if (Session["LoginUserRoleId"].ToString() == Resources.AdminRoleId)
            {
                <li>
                    <a href="#" class="waves-effect"><i class="linea-icon linea-basic fa-fw"></i> <span class="hide-menu">Project<span class="fa arrow"></span> </span></a>
                    <ul class="nav nav-second-level collapse" aria-expanded="true">
                        @*<li><a href="@Url.Action("GetDashboardMenu", "Dashboard", new { SelectedMenu = Resources.AddEmployee })">@Resources.AddEmployee</a></li>*@
                        <li><a href="@Url.Action("GetDashboardMenu", "Dashboard", new { SelectedMenu = Resources.AddProject })">@Resources.AddProject</a></li>
                        <li><a href="@Url.Action("GetProjectList", "Dashboard")">Project List</a></li>
                    </ul>
                </li>
            }

            <li>
                <a href="#" class="waves-effect"><i class="linea-icon linea-basic fa-fw"></i> <span class="hide-menu">Reports<span class="fa arrow"></span></span></a>
                <ul class="nav nav-second-level collapse" aria-expanded="true">
                    <li><a href="@Url.Action("GetWorkingHourList", "Dashboard")">Working Hour</a></li>
                    @*<li><a href="@Url.Action("GetEmployeeList", "Dashboard")">Employee List</a></li>*@

                    @*<li><a href="@Url.Action("GetDashboardMenu", "Dashboard", new { SelectedMenu = Resources.DefaulterList })">@Resources.DefaulterList</a></li>*@
                </ul>
            </li>

            <li>
                <a href="#" class="waves-effect"><i class="linea-icon linea-basic fa-fw"></i> <span class="hide-menu">Issue<span class="fa arrow"></span></span></a>
                <ul class="nav nav-second-level collapse" aria-expanded="true">
                    <li><a href="@Url.Action("Index", "ChatForum")">Add New Issue</a></li>
                    <li><a href="@Url.Action("GetChatForumDetailList", "ChatForum")">View Issue</a></li>
                </ul>
            </li>

            <li>
                <a href="@Url.Action("LogOut", "Dashboard")">Logout</a>
            </li>

        </ul>
    </div>
</div>